[package]
name = "dxtracker"
version = "0.1.2"
authors = ["hendrik@dd5ht.de"]
edition = "2018"

[dependencies]
clap = "*"
toml = "*"
csv = "*"
serde = { version = "*", features = ["derive"] }
dirs = "*"
regex = "*"

[profile.release]
lto = true