[package]
name = "dx-analyser"
version = "0.1.0"
authors = ["hendrik@dd5ht.de"]
autobins = false

[dependencies]
clap = "*"
toml = "*"
serde = "*"
serde_derive = "*"

[profile.release]
lto = false

[lib]
name = "dxtracker"
path = "src/lib.rs"

[[bin]]
name = "dxtool"
path = "src/bin.rs"