[package]
name = "dxtracker"
version = "0.1.2"
authors = ["hendrik@dd5ht.de"]

[dependencies]
clap = "*"
toml = "*"
csv = "*"
serde = "*"
serde_derive = "*"
dirs = "*"
regex = "*"

[profile.release]
lto = true